# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20161020145901 on 2016-12-05 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=200)),
                ('body_text', models.CharField(max_length=1000)),
            ],
        ),
    ]
