# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20161020145901 on 2016-12-09 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arxiv', '0002_auto_20161209_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='authors',
            field=models.ManyToManyField(to='arxiv.Author'),
        ),
    ]
