# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20161020145901 on 2016-12-09 12:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arxiv', '0004_article_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='pub_date',
        ),
    ]
